### PR TITLE
Improving error message to find the origin of null values

### PR DESCRIPTION
**Pull request by raandree**

### CODE REVIEW

**Comment by gaelcolas** [comment]
Please clean up your history, it's difficult to see what you actually changed.

**Comment by raandree** [comment]
It is just a simple single line adding some information to the exception message. If you click on "changes" it appears right away.

**Comment by raandree** [comment]
I see, there are old changes in the branch. How do I get rid of them? Just delete the whole fork?

**Comment by raandree** [comment]
"git pull --rebase" does not change anything. However this PR has only one little change. All the history should not have any effect, right?

**Pull request closed without merging**
